# Generated by Django 5.1 on 2024-08-14 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recipes',
            fields=[
                ('recipe_id', models.AutoField(primary_key=True, serialize=False)),
                ('recipe_name', models.TextField(blank=True, db_index=True, null=True)),
                ('image_filename', models.TextField(blank=True, null=True)),
                ('time_cook', models.IntegerField(blank=True, null=True)),
                ('ingridient', models.TextField(blank=True, null=True)),
                ('how_to_cook', models.TextField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(blank=True, null=True)),
                ('created_by', models.TextField(blank=True, null=True)),
                ('created_time', models.DateTimeField(blank=True, null=True)),
                ('modified_by', models.TextField(blank=True, null=True)),
                ('modified_time', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'recipes',
            },
        ),
    ]
