# Generated by Django 5.1 on 2024-08-15 07:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_category_difficulty_alter_recipes_image_filename'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='category',
            table='category',
        ),
        migrations.AlterModelTable(
            name='difficulty',
            table='difficulty',
        ),
    ]
