# Generated by Django 5.1 on 2024-08-15 07:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_recipes_category_recipes_categoryid_recipes_level_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipes',
            name='categoryId',
        ),
        migrations.RemoveField(
            model_name='recipes',
            name='levelId',
        ),
    ]
