# Generated by Django 5.1 on 2024-08-15 07:33

import django.db.models.fields.related
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0005_remove_recipes_categoryid_remove_recipes_levelid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipes',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.fields.related.ForeignKey, to='recipes.category'),
        ),
        migrations.AlterField(
            model_name='recipes',
            name='level',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.fields.related.ForeignKey, to='recipes.difficulty'),
        ),
    ]
