# Generated by Django 5.1 on 2024-08-15 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0007_alter_recipes_category_alter_recipes_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipes',
            name='is_favorite',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
