# Generated by Django 5.1 on 2024-08-15 09:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0008_recipes_is_favorite'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipes',
            name='is_deleted',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.CreateModel(
            name='FavoriteFood',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('is_favorite', models.BooleanField(blank=True, null=True)),
                ('Recipe', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='recipes.recipes')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'favorite_food',
            },
        ),
    ]
