# Generated by Django 5.1 on 2024-08-16 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0009_alter_recipes_is_deleted_favoritefood'),
    ]

    operations = [
        migrations.RenameField(
            model_name='favoritefood',
            old_name='Recipe',
            new_name='recipe',
        ),
        migrations.AlterField(
            model_name='favoritefood',
            name='is_favorite',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
    ]
